### ISSUE TITLE
執行後發生錯誤

### ISSUE THREAD

**Issue by ty002741** [jing-tw/climbing#8]
想請問一下...這個要如何排除
![image](https://user-images.githubusercontent.com/13043525/86096961-98619d80-bae6-11ea-8697-585adf887a11.png)

**Comment by jing-tw** [comment]
我剛剛用 Windows 重新安裝一次, 沒問題.

會不會沒有安裝 git?
驗證方式:
＝> 在 Anaconda Prompt 裡執行 git.  如果出現錯誤, 就是沒裝.

安裝 Windows git 的作法. 請執行下面的指令.
Step 1: Install git
https://git-scm.com/download/win
Note:  (下載 64-bit Git for Windows Setup).

Step 2: Clone the source
(a) 再重新啟動 Anaconda Prompt
(b) git clone https://github.com/jing-tw/autoclimb.git

Step 3: Run
python autoclimb.py

**Comment by jing-tw** [comment]
因為其他使用者都沒有這樣的問題, 自己也找了新的機器重新安裝了軟體. 正常執行. 因此, 如果你還有遇到問題. 請重新發 issue. 目前先 closed.

Thx
Jing.
